apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythontest
  namespace: pythontest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythontest
  template:
    metadata:
      labels:
        app: pythontest
    spec:
      containers:
      - name: pythontest
        image: mzazontrial.jfrog.io/docker-local/simpleapp:latest
        ports:
        - containerPort: 3000
