apiVersion: v1
kind: Service
metadata:
  name: pythontest-svc
  namespace: pythontest
spec:
  selector:
    app: pythontest
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
